name: deploy
on:
  push:
    branches:[master] # master 分支有push时触发
    paths-ignore:   # 下列文件的变更不触发部署，可自定添加
      - README.md
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 下载源码
      # 这一步就是检出你的仓库并下载里面的代码到 runner 中，actions/checkout@v4 是官方自己造的轮子，直接拿来使用
      - uses: actions/checkout@v4
        name: Checkout
      # 打包构建
      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: "16.x"
      - run: npm install # 安装依赖
      - run: npm run build # 打包
      # 部署到 github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3   # 使用部署到 github pages 的 action
      with:
          # 部署到 master 分支
          branch: master
          publish_dir: ./dist   # 部署打包后的dist目录
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: 自动部署  # 部署是的git提交信息，自由填写
